### ISSUE TITLE
no support ? are u down s3bubble ?

### ISSUE THREAD

**Issue by sribharathgupta** [s3bubble/Netflix-Theme#122]
Hi 
i have sent many emails no response yet 

how do i get our work started 

are u in for support or shall we see another provider

**Comment by s3bubble** [comment]
Hi @sribharathgupta,

We are preparing to run a new update shortly we will be removing the theme development from Github and into the S3bubble dashboard.

Please wait for our new updates to go through then we will get back to support you will see the updates and the new dashboard.

**Comment by sribharathgupta** [comment]
But we need to get started with our work .. can u just reply to emails atleast for now
